<?php

namespace Tests\Unit\Turn;

use App\Turn\StunMessage;
use PHPUnit\Framework\TestCase;
use RuntimeException;

class StunMessageTest extends TestCase
{
    // -------------------------------------------------------------------------
    // Binary fixture tests (external-source bytes — not generated by our codec)
    // -------------------------------------------------------------------------

    /**
     * Minimal STUN Binding Request — 20-byte header, no attributes.
     * Bytes hand-crafted from RFC 5389 §6 header layout.
     *
     * Hex: 000100002112a442000102030405060708090a0b
     */
    public function test_parse_binding_request_fixture(): void
    {
        $hex = '000100002112a442000102030405060708090a0b';
        $msg = StunMessage::parse(hex2bin($hex));

        $this->assertSame(StunMessage::BINDING_REQUEST, $msg->type);
        $this->assertSame(hex2bin('000102030405060708090a0b'), $msg->transactionId);
        $this->assertEmpty($msg->attributes);
    }

    /**
     * STUN Binding Response with XOR-MAPPED-ADDRESS for 192.168.1.1:12345.
     *
     * XOR-MAPPED-ADDRESS encoding (IPv4):
     *   port: 12345 (0x3039) XOR 0x2112 = 0x112b
     *   ip:   192.168.1.1 (0xC0A80101) XOR 0x2112A442 = 0xE1BAA543
     *
     * Response hex: 0101000c2112a442000102030405060708090a0b002000080001112be1baa543
     */
    public function test_parse_binding_response_with_xor_mapped_address(): void
    {
        $hex = '0101000c2112a442000102030405060708090a0b002000080001112be1baa543';
        $msg = StunMessage::parse(hex2bin($hex));

        $this->assertSame(StunMessage::BINDING_RESPONSE, $msg->type);

        $addr = $msg->getAttribute(StunMessage::ATTR_XOR_MAPPED_ADDRESS);
        $this->assertNotNull($addr);
        $this->assertSame('192.168.1.1', $addr['ip']);
        $this->assertSame(12345, $addr['port']);
    }

    public function test_parse_throws_on_too_short_buffer(): void
    {
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessageMatches('/too short/');

        StunMessage::parse(str_repeat("\x00", 19));
    }

    public function test_parse_throws_on_wrong_magic_cookie(): void
    {
        // Header with last byte of magic cookie incremented by 1 (0x2112A443)
        $hex = '000100002112a443000102030405060708090a0b';
        $this->expectException(RuntimeException::class);
        $this->expectExceptionMessageMatches('/magic cookie/i');

        StunMessage::parse(hex2bin($hex));
    }

    // -------------------------------------------------------------------------
    // Codec round-trip tests
    // -------------------------------------------------------------------------

    public function test_serialize_round_trip_binding_request(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::BINDING_REQUEST;
        $msg->transactionId = random_bytes(12);

        $parsed = StunMessage::parse($msg->serialize());

        $this->assertSame(StunMessage::BINDING_REQUEST, $parsed->type);
        $this->assertSame($msg->transactionId, $parsed->transactionId);
    }

    public function test_serialize_round_trip_with_xor_mapped_address(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::BINDING_RESPONSE;
        $msg->transactionId = random_bytes(12);
        $msg->addXorMappedAddress('10.0.0.5', 54321);

        $parsed = StunMessage::parse($msg->serialize());
        $addr = $parsed->getAttribute(StunMessage::ATTR_XOR_MAPPED_ADDRESS);

        $this->assertSame('10.0.0.5', $addr['ip']);
        $this->assertSame(54321, $addr['port']);
    }

    public function test_serialize_round_trip_error_code(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::ALLOCATE_ERROR;
        $msg->transactionId = random_bytes(12);
        $msg->addErrorCode(401, 'Unauthorised');

        $parsed = StunMessage::parse($msg->serialize());
        $err = $parsed->getAttribute(StunMessage::ATTR_ERROR_CODE);

        $this->assertSame(401, $err['code']);
        $this->assertSame('Unauthorised', $err['reason']);
    }

    public function test_xor_port_uses_high_16_bits_only(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::BINDING_RESPONSE;
        $msg->transactionId = random_bytes(12);
        $msg->addXorMappedAddress('1.2.3.4', 3478);

        $raw = $msg->serialize();

        // Header (20 bytes) + attr type (2) + attr length (2) = offset 24 is start of attr value
        // Attr value: family(1)+reserved(1)+port_xored(2)+ip_xored(4) — port is at offset 26
        $xorPort = unpack('n', substr($raw, 26, 2))[1];
        $decoded = $xorPort ^ 0x2112;

        $this->assertSame(3478, $decoded, 'Port must be XORed with 0x2112 (high 16 bits), not the full 32-bit magic cookie');
    }

    // -------------------------------------------------------------------------
    // HMAC / MESSAGE-INTEGRITY tests (critical protocol correctness)
    // -------------------------------------------------------------------------

    /**
     * Known-vector test: key derived from "flash:flashview.io:changeme" must be
     * the raw binary MD5 = 0x21e6f57cfaa5dc4d384022ad4fc832d4.
     */
    public function test_make_key_produces_raw_binary_md5(): void
    {
        $key = StunMessage::makeKey('flash', 'flashview.io', 'changeme');

        $this->assertSame(16, strlen($key), 'Key must be 16 raw bytes (binary MD5), not a 32-char hex string');
        $this->assertSame('21e6f57cfaa5dc4d384022ad4fc832d4', bin2hex($key));
    }

    /**
     * Known-vector test: HMAC-SHA1 over an empty body (Allocate Request, all-zero TXN)
     * with the known key must match the pre-computed value.
     *
     * Pre-computed:
     *   key    = hex2bin('21e6f57cfaa5dc4d384022ad4fc832d4')
     *   header = pack('nnNa12', 0x0003, 24, 0x2112A442, "\x00" x 12)
     *   HMAC   = hash_hmac('sha1', header, key, true) = 26438b3147e7b520153a8ef4a6f84333af410f88
     */
    public function test_message_integrity_known_vector(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::ALLOCATE_REQUEST;
        $msg->transactionId = str_repeat("\x00", 12);

        $key = StunMessage::makeKey('flash', 'flashview.io', 'changeme');
        $msg->addMessageIntegrity($key);

        $hmacStored = $msg->getAttribute(StunMessage::ATTR_MESSAGE_INTEGRITY);

        $this->assertSame(20, strlen($hmacStored), 'HMAC-SHA1 must be 20 bytes');
        $this->assertSame('26438b3147e7b520153a8ef4a6f84333af410f88', bin2hex($hmacStored));
    }

    public function test_verify_message_integrity_accepts_valid_hmac(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::ALLOCATE_REQUEST;
        $msg->transactionId = random_bytes(12);
        $msg->attributes[StunMessage::ATTR_USERNAME] = 'flash';

        $key = StunMessage::makeKey('flash', 'flashview.io', 'changeme');
        $msg->addMessageIntegrity($key);

        $this->assertTrue($msg->verifyMessageIntegrity($key));
    }

    public function test_verify_message_integrity_rejects_wrong_key(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::ALLOCATE_REQUEST;
        $msg->transactionId = random_bytes(12);

        $correctKey = StunMessage::makeKey('flash', 'flashview.io', 'changeme');
        $wrongKey = StunMessage::makeKey('flash', 'flashview.io', 'wrongpassword');

        $msg->addMessageIntegrity($correctKey);

        $this->assertFalse($msg->verifyMessageIntegrity($wrongKey));
    }

    public function test_verify_message_integrity_rejects_tampered_body(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::ALLOCATE_REQUEST;
        $msg->transactionId = random_bytes(12);
        $msg->attributes[StunMessage::ATTR_USERNAME] = 'flash';

        $key = StunMessage::makeKey('flash', 'flashview.io', 'changeme');
        $msg->addMessageIntegrity($key);

        // Tamper with the username after signing
        $msg->attributes[StunMessage::ATTR_USERNAME] = 'attacker';

        $this->assertFalse($msg->verifyMessageIntegrity($key));
    }

    public function test_verify_message_integrity_returns_false_when_missing(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::ALLOCATE_REQUEST;
        $msg->transactionId = random_bytes(12);

        $key = StunMessage::makeKey('flash', 'flashview.io', 'changeme');

        $this->assertFalse($msg->verifyMessageIntegrity($key));
    }

    // -------------------------------------------------------------------------
    // Attribute encoding
    // -------------------------------------------------------------------------

    public function test_lifetime_round_trip(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::ALLOCATE_RESPONSE;
        $msg->transactionId = random_bytes(12);
        $msg->addLifetime(600);

        $parsed = StunMessage::parse($msg->serialize());

        $this->assertSame(600, $parsed->getAttribute(StunMessage::ATTR_LIFETIME));
    }

    public function test_realm_and_nonce_round_trip(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::ALLOCATE_ERROR;
        $msg->transactionId = random_bytes(12);
        $msg->addRealm('flashview.io');
        $msg->addNonce('abc123');

        $parsed = StunMessage::parse($msg->serialize());

        $this->assertSame('flashview.io', $parsed->getAttribute(StunMessage::ATTR_REALM));
        $this->assertSame('abc123', $parsed->getAttribute(StunMessage::ATTR_NONCE));
    }

    public function test_xor_relayed_address_round_trip(): void
    {
        $msg = new StunMessage;
        $msg->type = StunMessage::ALLOCATE_RESPONSE;
        $msg->transactionId = random_bytes(12);
        $msg->addXorRelayedAddress('203.0.113.1', 49152);

        $parsed = StunMessage::parse($msg->serialize());
        $addr = $parsed->getAttribute(StunMessage::ATTR_XOR_RELAYED_ADDRESS);

        $this->assertSame('203.0.113.1', $addr['ip']);
        $this->assertSame(49152, $addr['port']);
    }
}
