export {
    generatePassphrase,
    encryptMessage,
    decryptMessage,
    encryptBuffer,
    decryptBuffer,
    generateTransferKey,
    generateSessionId,
    generateIdentityKeypair,
    encryptKeyForDevice,
    decryptKeyFromDevice,
    computePairingCode,
    encryptChunk,
    decryptChunk,
    encryptToBlob,
    encryptFileToBlob,
    decryptFromBlob,
    deriveAuthKey,
    computeVerifier,
    LockerBlobVersionError,
    LockerDecryptionError,
} from '@pioneer-dynamics/flashview-crypto';
