name: CLI Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    paths:
      - 'tools/flashview-cli/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/flashview-cli

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm ci

      - run: npm test
