name: CLI Tests

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - master
    paths:
      - 'tools/flashview-cli/**'
      - 'tools/flashview-crypto/**'

jobs:
  crypto-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: tools/flashview-crypto
        run: npm ci

      - name: Run tests
        working-directory: tools/flashview-crypto
        run: npm test

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install crypto package dependencies
        working-directory: tools/flashview-crypto
        run: npm ci

      - name: Install CLI dependencies
        working-directory: tools/flashview-cli
        run: npm ci

      - name: Run tests
        working-directory: tools/flashview-cli
        run: npm test
